
title: UnderJS Podcast
email: talk@underjs.ru
description: >- # this means to ignore newlines until "baseurl:"
  UnderJS podcast – самый безызвестный подкаст во всем frontend. Underground уже тут.
baseurl: ""
url: "https://underjs.ru"

twitter_username: underjs
github_username:  underjs

author:
  name: "Дмитрий Пацура, Артём Кобзарь"
  twitter: ovrweb

# Misc
license: CC-BY-CA

twitter:
  username: underjs
  creator: ovrweb
  card: summary

# Podcast
podcast:
  title: UnderJS Podcast
  author: Дмитрий Пацура, Артём Кобзарь
  link: https://underjs.ru/
  art: https://underjs.ru/assets/images/logo-1400px.jpg
  category: Technology
  subtitle: "UnderJS podcast – самый безызвестный подкаст во всем frontend. Underground уже тут."
  summary: >
    UnderJS podcast – самый безызвестный подкаст во всем frontend. Underground уже тут.

sc_player:
  auto_play: false
  buying: true
  liking: true
  download: true
  sharing: true
  show_artwork: true
  show_comments: true
  show_playcount: true
  show_user: true
  start_track: 0

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-twitter-plugin
  - jekyll-sitemap
  - jekyll-seo-tag
