
title: UnderJS Podcast
email: talk@underjs.ru
description: >- # this means to ignore newlines until "baseurl:"
  UnderJS podcast – самый безызвестный подкаст во всем frontend. Underground уже тут.
baseurl: ""
url: ""
twitter_username: underjs
github_username:  ovrweb

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-twitter-plugin
  - jekyll-sitemap
  - jekyll-seo-tag
